<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <OutputType>Library</OutputType>
    <RootNamespace>QuantumRelay</RootNamespace>
    <AssemblyName>QuantumRelay</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Authors>SockedRooster</Authors>
    <Company>RoosterWorks</Company>
    <Product>Quantum Relay</Product>
    <Description>True stock CommNet routing through Promised Worlds wormholes.</Description>
    <Copyright>Copyright © 2026 RoosterWorks</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.2.0-alpha4</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.4</FileVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <KSPRoot Condition=" '$(KSPRoot)' == '' ">A:\SteamLibrary\steamapps\common\Kerbal Space Program</KSPRoot>
    <KSPManaged Condition=" '$(KSPManaged)' == '' ">$(KSPRoot)\KSP_x64_Data\Managed</KSPManaged>
    <OutputPath>..\..\GameData\QuantumRelay\Plugins\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(KSPManaged)\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(KSPManaged)\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(KSPManaged)\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(KSPManaged)\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AnimationModule"><HintPath>$(KSPManaged)\UnityEngine.AnimationModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
